### ISSUE TITLE
Problem with rosrun summer_gazebo send_summer.py  

### ISSUE THREAD

**Issue by johnreb20** [sunghowoo/Control-of-two-UR5s-by-two-phantom-omnies-#2]
Hi,
I using a single omni device and using rosrun summer_gazebo send_summer.py , but there is no output just blank using ros medolic.
Thanks, waiting for your reply.
Regards,
John Rebeiro

**Comment by sunghowoo** [comment]
Dear John,
please check the environment. I used  ROS Kinetic, not Melodic.
I guess **you should find a proper driver version** that can communicate with Melodic.
Best wishes,
Sungho

**Comment by johnreb20** [comment]
Dear Sungho,
I used a single Phantom Omni connected with the system with a USB A to B cable.The rviz (i.e roslaunch geomagic_control geomagic.launch) and gazebo of a single UR5 (i.e roslaunch summer_gazebo summer_robot.launch) worked fine. But only the communication part was giving a blank output.
Thanks for your quick response. I will try it on ROS kinetic.Did you use a single Omni Device?
Regards,
John Rebeiro

**Comment by sunghowoo** [comment]
Dear John,
I also used a single Omni. I  had a black output problem due to an improper driver version. 
Good luck.
Best wishes
Sungho.

**Comment by johnreb20** [comment]
Dear Sungho,
It worked on ROS Melodic, actually, I didn't start the Gazebo sim time, that was my mistake. The Table is out of the robot workspace so have to shift it to try the force feedback case.
Thank You for your quick response and help.
Best Wishes,
John Rebeiro
